### ISSUE TITLE
Applicability to non-orthogonal image pairs

### ISSUE THREAD

**Issue by sarahmhooper** [dek924/PerX2CT#19]
Hi, thank you very much for your paper and code, I've really enjoyed learning about it. I have a similar problem I'm working on, however my images are not orthogonal to one another---they can vary by what angle offset they are from one another, their FOV, etc. I'm curious if this method (and the 2D-to-3D module) is applicable in this case? Thanks!

**Comment by dek924** [comment]
Hi, @sarahmhooper.

Thank you for your interest. Since we use orthogonal images, we set the camera pose as follows, specifying pitch and yaw for each:

```
self.mapping_camera_type2pose = {
            "PA": torch.tensor([0, 0]),
            "Lateral": torch.tensor([math.pi / 2, math.pi / 2]),
        }
```

In your case, you might try adjusting the camera pose in `x2ct_nerf.data.base.LIDCMultiInputMultiResTypes` or possibly modifying the FOV settings in the configuration. This approach could potentially achieve the result you’re aiming for. For more details, please refer to the `x2ct_nerf.modules.inr.model.PerspectiveINRNet.convert_feature_from2d_to3d` function.
